Add Rate this App button on menu screen
codeforbtv/green-up-app-old pull request #38
Opened 2018-10-19 00:23 UTC by kbeaulieu802

Add a `Rate this App` button on the menu screen that directs users to the app store or play store to leave a review of the app.

2018-10-19 12:57 UTC, smaraf commented on screens/menu-screen/index.js
> +                          if(Platform.OS == 'ios'){
you'll need to add 
```suggestion
                          import { Platform } from 'react-native'
```
at the top of this file, otherwise, when clicking the Review this App button the app crashes with ```Can't find variable: Platform```

2018-10-19 13:00 UTC, smara-codes requested changes
There's one issue when running on iOS, the app crashes when clicking the 'Review this App' - it's likely just the import missing.

2018-10-20 00:17 UTC, kbeaulieu802 commented on screens/menu-screen/index.js
> +                          if(Platform.OS == 'ios'){
@smaraf, Sorry about this. I thought i checked this before creating the PR.

2018-10-20 13:47 UTC, smara-codes approved these changes
Looking good!

2018-10-20 13:48 UTC, merged

2018-10-20 13:48 UTC, smaraf commented on screens/menu-screen/index.js
> +                          if(Platform.OS == 'ios'){
No worries. It works great now.