Supply distribution data issue#376
codeforbtv/green-up-app-old pull request #380
Opened 2020-05-17 14:44 UTC by iritush

replace references to trashCollectionSites with supplyDistributionSites

2020-05-17 15:51 UTC, doub1ejack requested changes
Irit, this is great except for one bug.  

I'd love to get this deployed out to QA today (and Prod by tomorrow morning), along with a version bump.  If you don't have time to bump the version and make the code change before ~6pm tonight, just let me know and I can take care of it.

2020-05-17 15:51 UTC, doub1ejack commented on functions/api.js
> +        [editable => typeof editable === "string" && editable.toLowerCase() === "false", () => R.filter(supplyDistributionSite => !permittedTowns.includes(trashCollectionSite.townId))],
I believe the R.filter function provided here will need to be updated with `supplyDistributionSite.townId` since the input param has changed:
```R.filter(supplyDistributionSite => !permittedTowns.includes(trashCollectionSite.townId)```

If this has been deployed I expect it would return empty results, and I think the way the supply distribution screen is set up an empty result will simply break. This might have been the issue that @nfloersch mentioned to me this morning in slack.

2020-05-17 15:51 UTC, doub1ejack commented on functions/api.js
> +        [editable => editable === true, () => R.filter(supplyDistributionSite => permittedTowns.includes(supplyDistributionSite.townId))],
There was talk in Slack about the api retrieving the wrong data, but this is a non-functional change and wouldn't change any behavior.  I did a couple double-takes at this code the other night before I realized that this...
`R.filter(supplyDistributionSite => permittedTowns.includes(supplyDistributionSite.townId)`
... is the same as this
`R.filter(x => permittedTowns.includes(x.townId)`

But regardless, this still a good fix (IMO) because the current code is confusing & misleading.

2020-05-17 15:51 UTC, doub1ejack commented on reducers/supply-distribution-sites-reducers.js
> +        case types.FETCH_SUPPLY_DISTRIBUTION_SITES_SUCCESS :
This is the crucial change - we were literally firing off the wrong action when trying to retrieve data.  I've made this change locally and I'm seeing the correct data (including supply distribution notes) from the admin tool displayed in the app 👏 
<img src="https://user-images.githubusercontent.com/1809882/82153190-018d9a00-9834-11ea-972f-8f464cc5233a.png" width="400"/>

2020-05-17 16:09 UTC, iritush commented on reducers/supply-distribution-sites-reducers.js
> +        case types.FETCH_SUPPLY_DISTRIBUTION_SITES_SUCCESS :
I agree. This is the behavior I was seeing locally as well. I am inclined to reverse the api changes in the QA env for now and focus on this fix first, to be able to get the new device version going. Then, move on to the back end changes which can be deployed without the testers needing to update to a new version. Let me know what you think.

2020-05-17 16:11 UTC, iritush commented on functions/api.js
> +        [editable => typeof editable === "string" && editable.toLowerCase() === "false", () => R.filter(supplyDistributionSite => !permittedTowns.includes(trashCollectionSite.townId))],
Very possible. I didn't really know what I was doing the :-). Happy to revert this

2020-05-17 18:55 UTC, iritush commented on reducers/supply-distribution-sites-reducers.js
> +        case types.FETCH_SUPPLY_DISTRIBUTION_SITES_SUCCESS :
I created a new branch & PR for this fix so that it can be merged and built: https://github.com/codeforbtv/green-up-app/pull/382

2020-05-21 02:16 UTC, doub1ejack commented
@iritush, I think this PR can be closed now, right?  Is there anything here that didn't get carried over?

2020-05-21 13:14 UTC, iritush commented
I think that the only change that ended up being merged to Master was the reducer one. I will confirm in a bit and update

2020-05-21 19:37 UTC, iritush commented
I checked master and the changes to api.js in this PR also made it to the master branch. Since it is just variable name changes it is probably fine to just leave it there. If you agree please feel free to close it @doub1ejack

2020-05-27 14:31 UTC, doub1ejack commented
Closing this b/c @iritush created another branch (#382) that has been merged and addresses the substantive parts of this PR.

2020-05-27 14:31 UTC, closed without merging